name: "Dependent Jobs in GitHub Actions"

on: [push, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "Job 1 successfully runs"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2
        shell: bash
        run: echo "Job 2 successfully runs"

  job3:
    runs-on: macos-latest
    needs: [job1, job2]
    steps:
      - name: Job 3
        shell: zsh
        run: echo "Job 3 successfully runs"
